
;----------------------------------------------------------------------------------------------------------------------------------------------------------------
;请勿二次传播转发，本平台用于EC整合包开发组合
;存在开发中内容和待测试内容，但本平台完全公开
;如只需在模组使用部分功能，请自行合并需要的内容
;对于未发布pr的内容，请前往作者的github页面查找
;对于需要反馈问题，请联系作者以寻求解决方案
;                                    - by 緋紅熱茶
;----------------------------------------------------------------------------------------------------------------------------------------------------------------

;【注意】引用的图像、武器、弹头自行补充

; A.手枪
[SOMEPROJECTILEA1]
AA=no
AG=yes
Inaccurate=yes
BallisticScatter.Min=0
BallisticScatter.Max=0.5
SubjectToCliffs=yes
SubjectToElevation=yes
SubjectToWalls=yes
SubjectToBuildings=yes
SubjectToGround=yes
Image=SOMEIMAGEA1
Trajectory=Straight
Trajectory.Straight.DetonationDistance=0
Trajectory.Straight.TargetSnapDistance=0
Trajectory.Speed=400.0
Airburst=yes
AirburstWeapon=SOMEWEAPONA2
Cluster=1
AirburstSpread=0.5

; B.霰弹枪
[SOMEPROJECTILEB1]
AA=no
AG=yes
SubjectToCliffs=yes
SubjectToElevation=no
SubjectToWalls=yes
SubjectToBuildings=yes
SubjectToGround=yes
Image=SOMEIMAGEB1
Trajectory=Missile
Trajectory.Missile.LaunchSpeed=0
Trajectory.Missile.Acceleration=0
Trajectory.Missile.TurningSpeed=0
Trajectory.Missile.LockDirection=yes
Trajectory.DisperseSuicide=yes
Trajectory.DisperseWeapons=SOMEWEAPONB2
Trajectory.DisperseBursts=5
Trajectory.DisperseCounts=1
Trajectory.Speed=0

[SOMEPROJECTILEB2]
AA=no
AG=yes
SubjectToCliffs=yes
SubjectToElevation=no
SubjectToWalls=yes
SubjectToBuildings=yes
SubjectToGround=no
Image=SOMEIMAGEB2
Trajectory=Straight
Trajectory.ApplyRangeModifiers=yes
Trajectory.Straight.RotateCoord=10
Trajectory.UseDisperseBurst=yes
Trajectory.Straight.DetonationDistance=-0.5
Trajectory.Straight.TargetSnapDistance=0
Trajectory.Straight.PassThrough=yes
Trajectory.ProximityImpact=1
Trajectory.ProximityWarhead=SOMEWARHEADB2
Trajectory.ProximityDamage=50
Trajectory.ProximityRadius=0.4
Trajectory.ProximityDirect=yes
Trajectory.ThroughVehicles=no
Trajectory.ThroughBuilding=no
Trajectory.DamageEdgeAttenuation=0.6
Trajectory.Speed=300.0
Airburst=yes
AirburstWeapon=SOMEWEAPONB3
Cluster=1
AirburstSpread=0.5

; C.光翼展开
[SOMEPROJECTILEC1]
AA=yes
AG=yes
SubjectToCliffs=no
SubjectToElevation=no
SubjectToWalls=no
SubjectToBuildings=no
SubjectToGround=no
Image=SOMEIMAGEC1
Trajectory=Missile
Trajectory.Missile.PreAimCoord=0,200,250
Trajectory.Missile.ReduceCoord=no
Trajectory.Missile.RotateCoord=120
Trajectory.Missile.AxisOfRotation=-1,0,0
Trajectory.Missile.LaunchSpeed=50
Trajectory.Missile.Acceleration=10
Trajectory.Missile.TurningSpeed=20
Trajectory.RetargetRadius=4
Trajectory.Speed=250.0

; D.喷火器
[SOMEPROJECTILED1]
AA=no
AG=yes
Inaccurate=yes
BallisticScatter.Min=0.8
BallisticScatter.Max=1.2
SubjectToCliffs=yes
SubjectToElevation=no
SubjectToWalls=yes
SubjectToBuildings=yes
SubjectToGround=no
Image=SOMEIMAGED1
Trajectory=Straight
Trajectory.ApplyRangeModifiers=yes
Trajectory.Straight.DetonationDistance=4.7
Trajectory.Straight.TargetSnapDistance=0
Trajectory.Straight.PassThrough=yes
Trajectory.ProximityImpact=-1
Trajectory.ProximityWarhead=SOMEWARHEADD1
Trajectory.ProximityDamage=40
Trajectory.ProximityRadius=0.8
Trajectory.ProximityDirect=yes
Trajectory.ProximityAllies=yes
Trajectory.ThroughVehicles=no
Trajectory.ThroughBuilding=no
Trajectory.Straight.ConfineAtHeight=75
Trajectory.Speed=60.0

; E.重机枪
[SOMEPROJECTILEE1]
AA=no
AG=yes
Inaccurate=yes
BallisticScatter.Min=0.25
BallisticScatter.Max=0.75
SubjectToCliffs=yes
SubjectToElevation=no
SubjectToWalls=yes
SubjectToBuildings=yes
SubjectToGround=yes
Image=SOMEIMAGEE1
Trajectory=Straight
Trajectory.ApplyRangeModifiers=yes
Trajectory.Straight.DetonationDistance=-0.5
Trajectory.Straight.TargetSnapDistance=0
Trajectory.Straight.PassThrough=yes
Trajectory.ProximityImpact=3
Trajectory.ProximityWarhead=SOMEWARHEADE1
Trajectory.ProximityDamage=40
Trajectory.ProximityRadius=0.4
Trajectory.ProximityDirect=yes
Trajectory.ThroughBuilding=no
Trajectory.DamageEdgeAttenuation=0.75
Trajectory.Speed=300.0

; F.地锤
[SOMEPROJECTILEF1]
AA=no
AG=yes
Inaccurate=yes
BallisticScatter.Min=0
BallisticScatter.Max=1
SubjectToCliffs=no
SubjectToElevation=no
SubjectToWalls=no
SubjectToBuildings=no
SubjectToGround=no
Image=SOMEIMAGEF1
Trajectory=Straight
Trajectory.ApplyRangeModifiers=yes
Trajectory.Straight.DetonationDistance=12.5
Trajectory.Straight.TargetSnapDistance=0
Trajectory.Straight.PassThrough=yes
Trajectory.PassDetonate=yes
Trajectory.PassDetonateWarhead=SOMEWARHEADF1
Trajectory.PassDetonateDamage=60
Trajectory.PassDetonateDelay=5
Trajectory.PassDetonateInitialDelay=1
Trajectory.PassDetonateLocal=yes
Trajectory.Straight.ConfineAtHeight=32
Trajectory.Speed=60.0
Airburst=yes
AirburstWeapon=SOMEWEAPONF2
Cluster=1
AirburstSpread=0.5

; G.炮射导弹
[SOMEPROJECTILEG1]
AA=yes
AG=yes
SubjectToCliffs=no
SubjectToElevation=no
SubjectToWalls=no
SubjectToBuildings=no
SubjectToGround=no
Image=SOMEIMAGEG1
Trajectory=Missile
Trajectory.Missile.LaunchSpeed=50
Trajectory.Missile.Acceleration=50
Trajectory.Missile.TurningSpeed=30
Trajectory.RetargetRadius=2.5
Trajectory.Speed=150.0

; H.扇形冲击波
[SOMEPROJECTILEH1]
AA=no
AG=yes
SubjectToCliffs=no
SubjectToElevation=no
SubjectToWalls=no
SubjectToBuildings=no
SubjectToGround=no
Image=SOMEIMAGEH1
Trajectory=Missile
Trajectory.Missile.LaunchSpeed=0
Trajectory.Missile.Acceleration=0
Trajectory.Missile.TurningSpeed=0
Trajectory.Missile.LockDirection=yes
Trajectory.DisperseWeapons=SOMEWEAPONH2
Trajectory.DisperseBursts=1
Trajectory.DisperseCounts=1
Trajectory.Speed=0

[SOMEPROJECTILEH2]
AA=no
AG=yes
SubjectToCliffs=no
SubjectToElevation=no
SubjectToWalls=no
SubjectToBuildings=no
SubjectToGround=no
Image=SOMEIMAGEH2
Trajectory=Missile
Trajectory.Missile.LaunchSpeed=0
Trajectory.Missile.Acceleration=0
Trajectory.Missile.TurningSpeed=0
Trajectory.Missile.LockDirection=yes
Trajectory.DisperseWeapons=SOMEWEAPONH3
Trajectory.DisperseBursts=8
Trajectory.DisperseCounts=1
Trajectory.DisperseInitialDelay=100
Trajectory.Speed=0

[SOMEPROJECTILEH3]
AA=no
AG=yes
SubjectToCliffs=no
SubjectToElevation=no
SubjectToWalls=no
SubjectToBuildings=no
SubjectToGround=no
Image=SOMEIMAGEH3
Trajectory=Straight
Trajectory.ApplyRangeModifiers=yes
Trajectory.Straight.DetonationDistance=9.2
Trajectory.Straight.TargetSnapDistance=0
Trajectory.Straight.PassThrough=yes
Trajectory.PassDetonate=yes
Trajectory.PassDetonateWarhead=SOMEWARHEADH3
Trajectory.PassDetonateDamage=60
Trajectory.PassDetonateDelay=6
Trajectory.PassDetonateInitialDelay=15
Trajectory.PassDetonateLocal=yes
Trajectory.Straight.OffsetCoord=10,0,1
Trajectory.MirrorCoord=no
Trajectory.Straight.RotateCoord=70
Trajectory.UseDisperseBurst=yes
Trajectory.DamageEdgeAttenuation=2.5
Trajectory.Straight.ConfineAtHeight=500
Trajectory.Speed=40.0

; J.激光扫射
[SOMEPROJECTILEJ1]
AA=no
AG=yes
SubjectToCliffs=yes
SubjectToElevation=yes
SubjectToWalls=no
SubjectToBuildings=no
SubjectToGround=yes
Image=SOMEIMAGEJ1
Trajectory=Engrave
Trajectory.PassDetonate=yes
Trajectory.PassDetonateDelay=2
Trajectory.Engrave.SourceCoord=0,300
Trajectory.Engrave.TargetCoord=0,-300
Trajectory.Engrave.IsIntense=yes
Trajectory.Engrave.IsSingleColor=yes
Trajectory.Engrave.LaserInnerColor=255,0,0
Trajectory.Speed=40.0

; K.滚珠
[SOMEPROJECTILEK1]
AA=no
AG=yes
SubjectToCliffs=yes
SubjectToElevation=yes
SubjectToWalls=no
SubjectToBuildings=no
SubjectToGround=no
Image=SOMEIMAGEK1
Gravity=4.0
Trajectory=Parabola
Trajectory.Speed=50.0
Trajectory.Parabola.DetonationDistance=0
Trajectory.Parabola.TargetSnapDistance=0
Trajectory.Parabola.OpenFireMode=SpeedAndAngle
Trajectory.Parabola.LaunchAngle=10
Trajectory.Parabola.BounceTimes=3
Trajectory.Parabola.BounceDetonate=yes
Trajectory.Parabola.OffsetCoord=0,80,0
Trajectory.Parabola.RotateCoord=30

; L.双联喷火器
[SOMEPROJECTILEL1]
AA=no
AG=yes
Inaccurate=yes
BallisticScatter.Min=0
BallisticScatter.Max=0.6
SubjectToCliffs=yes
SubjectToElevation=no
SubjectToWalls=yes
SubjectToBuildings=yes
SubjectToGround=no
Image=SOMEIMAGEL1
Trajectory=Straight
Trajectory.Straight.DetonationDistance=5.2
Trajectory.Straight.TargetSnapDistance=0
Trajectory.Straight.PassThrough=yes
Trajectory.Straight.OffsetCoord=0,115,0
Trajectory.ProximityImpact=-1
Trajectory.ProximityWarhead=SOMEWARHEADL1
Trajectory.ProximityDamage=40
Trajectory.ProximityRadius=0.8
Trajectory.ProximityDirect=yes
Trajectory.ProximityAllies=yes
Trajectory.ThroughBuilding=no
Trajectory.Straight.ConfineAtHeight=105
Trajectory.Speed=60.0

; M.垂发导弹
[SOMEPROJECTILEM1]
AA=yes
AG=yes
SubjectToCliffs=no
SubjectToElevation=no
SubjectToWalls=no
SubjectToBuildings=no
SubjectToGround=no
Image=SOMEIMAGEM1
Trajectory=Missile
Trajectory.Missile.PreAimCoord=0,0,100
Trajectory.Missile.LaunchSpeed=20
Trajectory.Missile.Acceleration=6
Trajectory.RetargetRadius=5
Trajectory.Speed=200.0

; N.定向激光扫射
[SOMEPROJECTILEN1]
AA=no
AG=yes
SubjectToCliffs=yes
SubjectToElevation=no
SubjectToWalls=no
SubjectToBuildings=no
SubjectToGround=no
Image=SOMEIMAGEN1
Trajectory=Engrave
Trajectory.PassDetonate=yes
Trajectory.PassDetonateDelay=2
Trajectory.Duration=75
Trajectory.Engrave.IsSingleColor=yes
Trajectory.Engrave.LaserInnerColor=255,50,255
Trajectory.Engrave.LaserThickness=6
Trajectory.Engrave.LaserDuration=6
Trajectory.Speed=40.0

; O.开花弹
[SOMEPROJECTILEO1]
AA=no
AG=yes
SubjectToCliffs=no
SubjectToElevation=yes
SubjectToWalls=no
SubjectToBuildings=no
SubjectToGround=no
Image=SOMEIMAGEO1
Trajectory=Parabola
Trajectory.Parabola.DetonationDistance=0.4
Trajectory.Parabola.TargetSnapDistance=0.5
Trajectory.Parabola.OpenFireMode=Speed
Trajectory.Speed=300.0
Gravity=16.0
Airburst=yes
AirburstWeapon=SOMEWEAPONO2
AirburstSpread=0.5
Cluster=1

[SOMEPROJECTILEO2]
AA=no
AG=yes
SubjectToCliffs=no
SubjectToElevation=no
SubjectToWalls=no
SubjectToBuildings=no
SubjectToGround=no
Image=SOMEIMAGEO2
Trajectory=Missile
Trajectory.Missile.TargetSnapDistance=0.8
Trajectory.Missile.PreAimCoord=0,0,1
Trajectory.Missile.LaunchSpeed=0
Trajectory.Missile.Acceleration=0
Trajectory.Missile.TurningSpeed=0
Trajectory.Missile.LockDirection=yes
Trajectory.DisperseWeapons=SOMEWEAPONO3
Trajectory.DisperseBursts=12
Trajectory.DisperseCounts=1
Trajectory.DisperseEffectiveRange=-1
Trajectory.Speed=0

[SOMEPROJECTILEO3]
AA=no
AG=yes
SubjectToCliffs=no
SubjectToElevation=no
SubjectToWalls=no
SubjectToBuildings=no
SubjectToGround=no
Image=SOMEIMAGEO3
Trajectory=Parabola
Trajectory.Parabola.DetonationDistance=0
Trajectory.Parabola.TargetSnapDistance=0
Trajectory.Parabola.OpenFireMode=SpeedAndAngle
Trajectory.Parabola.LaunchAngle=60
Trajectory.Parabola.BounceTimes=3
Trajectory.Parabola.BounceOnWater=yes
Trajectory.Parabola.BounceDetonate=yes
Trajectory.Parabola.BounceAttenuation=0.9
Trajectory.Parabola.BounceCoefficient=0.9
Trajectory.Parabola.OffsetCoord=10,0,1
Trajectory.Parabola.RotateCoord=330
Trajectory.MirrorCoord=no
Trajectory.UseDisperseBurst=yes
Trajectory.Speed=40.0
Gravity=8.0

; P.集束火炮
[SOMEPROJECTILEP1]
AA=no
AG=yes
SubjectToCliffs=no
SubjectToElevation=yes
SubjectToWalls=no
SubjectToBuildings=no
SubjectToGround=no
Image=SOMEIMAGEP1
Trajectory=Parabola
Trajectory.Parabola.DetonationDistance=-1
Trajectory.Parabola.TargetSnapDistance=0
Trajectory.Parabola.OpenFireMode=Height
Trajectory.Parabola.ThrowHeight=1600
Trajectory.Parabola.DetonationAngle=0
Gravity=6.0
RetargetAccuracy=1
Splits=yes
Airburst=yes
AirburstWeapon=SOMEWEAPONP2
AirburstSpread=0.5
Cluster=1

[SOMEPROJECTILEP2]
AA=no
AG=yes
SubjectToCliffs=no
SubjectToElevation=no
SubjectToWalls=no
SubjectToBuildings=no
SubjectToGround=no
Image=SOMEIMAGEP2
Trajectory=Missile
Trajectory.Missile.PreAimCoord=1,0,0
Trajectory.Missile.FacingCoord=yes
Trajectory.Missile.LaunchSpeed=0
Trajectory.Missile.Acceleration=0
Trajectory.Missile.TurningSpeed=0
Trajectory.Missile.LockDirection=yes
Trajectory.DisperseWeapons=SOMEWEAPONP3
Trajectory.DisperseBursts=3
Trajectory.DisperseCounts=1
Trajectory.DisperseRetarget=yes
Trajectory.Speed=0

[SOMEPROJECTILEP3]
AA=no
AG=yes
SubjectToCliffs=no
SubjectToElevation=no
SubjectToWalls=no
SubjectToBuildings=no
SubjectToGround=no
Image=SOMEIMAGEP3
Trajectory=Parabola
Trajectory.Parabola.DetonationDistance=0.2
Trajectory.Parabola.TargetSnapDistance=0.2
Trajectory.Parabola.OpenFireMode=Height
Trajectory.Parabola.ThrowHeight=1
Gravity=6.0

; Q.浮游炮
[SOMEPROJECTILEQ1]
AA=no
AG=yes
SubjectToCliffs=no
SubjectToElevation=no
SubjectToWalls=no
SubjectToBuildings=no
SubjectToGround=no
Image=SOMEIMAGEQ1
Trajectory=Tracing
Trajectory.Tracing.TraceMode=RotateCW
Trajectory.Duration=150
Trajectory.BulletROT=3
Trajectory.PeacefulVanish=yes
Trajectory.Tracing.TraceTheTarget=no
Trajectory.Tracing.OffsetCoord=520,0,400
Trajectory.DisperseCoord=100,0,0
Trajectory.DisperseFromFirer=no
Trajectory.DisperseWeapons=SOMEWEAPONQ1
Trajectory.DisperseCounts=1
Trajectory.DisperseDelays=24
Trajectory.DisperseInitialDelay=30
Trajectory.DisperseFaceCheck=yes
Trajectory.Speed=45.0
