name: Pull Request Check

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled
env:
  BASE_BRANCH: ${{ github.event.pull_request.base.ref }}

jobs:
  FilePath-Check:
    name: FilePath Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 验证并检查变更日志
        run: |
          # export LANG=en_US.UTF-8

          if [ ! -f "整合包说明/更新改动说明.md" ];
          then
            echo "❌ 文件不存在！实际路径结构："
            ls -R
            exit 1
          fi

          if ! git ls-files --error-unmatch "整合包说明/更新改动说明.md" >/dev/null 2>&1;
          then
            echo "❌ Git 未跟踪该文件！使用以下命令添加："
            echo "git add '整合包说明/更新改动说明.md'"
            exit 1
          fi

          if [ ! -f "整合包说明/额外功能说明.md" ];
          then
            echo "❌ 文件不存在！实际路径结构："
            ls -R
            exit 1
          fi

          if ! git ls-files --error-unmatch "整合包说明/额外功能说明.md" >/dev/null 2>&1;
          then
            echo "❌ Git 未跟踪该文件！使用以下命令添加："
            echo "git add '整合包说明/额外功能说明.md'"
            exit 1
          fi

  Changelog-Check:
    name: Changelog Mention
    # If the Minor label is set, then workflow will not be executed
    if: false == contains(github.event.pull_request.labels.*.name, 'Minor')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Check that Changelog has been updated
        run: |
          # Check that Changelog has been updated
          BASE_REF=${{ github.event.pull_request.base.sha }}
          if (git diff --name-only $(git merge-base origin/$BASE_BRANCH HEAD) | grep -q '^整合包说明/更新改动说明.md$')
          then
            echo "感谢您记得更新变更日志！😋"
            exit 0
          else
            echo "你好像忘了更新变更日志！🧐"
            echo "请在“整合包说明/更新改动说明”中提及您的更改。"
            exit 1
          fi

  Documentation-Check:
    name: Documentation for Changes
    # If the Minor label is set, then workflow will not be executed
    if: false == contains(github.event.pull_request.labels.*.name, 'Minor')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Check that Documentation has been updated
        run: |
          # Check that Documentation has been updated
          BASE_REF=${{ github.event.pull_request.base.sha }}
          if (git diff --name-only $(git merge-base origin/$BASE_BRANCH HEAD) | grep -q '^整合包说明/额外功能说明.md$')
          then
            echo "感谢您记得更新功能说明！😋"
            exit 0
          else
            echo "你好像忘了更新功能说明！🧐"
            echo "请在“整合包说明/额外功能说明”中提及您的更改。"
            exit 1
          fi
